//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListFilms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Films_tb
    {
        public int id { get; set; }
        public string title { get; set; }
        public string budget { get; set; }
        public Nullable<int> rating { get; set; }
        public string country { get; set; }
        public string genres { get; set; }
    }
}
